#!/usr/bin/env bash
read -p "Please Enter The text file:" FILENAME
cat << EOF > $FILENAME
 #!/usr/bin/env bash
 #Purpose: Here Document Exaple
 #Version: 1.0
 #Created Date: $(date)
 #Modified Date:
 #Website: http://nag.co.in
 #Author: Nageswara Rao
 usage() {
 echo "$FILENAME ARG1 OPER ARG2"
 }
 usage
 #START#
 #END#
EOF
